#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// actually 5 sec lol

void set_motors(int b, int c);

task main() {
	int threshold = 48;
	bool good = true;
	clearTimer(T1);
	while (good) {
		set_motors(5, 20);
		while (SensorValue(light) > threshold) {
			set_motors(20, 5);
		}
		if (time1[T1] > 5000) {
			good = false;
		}
	}
}

void set_motors(int b, int c) {
	motor[motorB] = b;
	motor[motorC] = c;
}
