#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// 48 threshold

void set_motors(int b, int c);

task main() {
	int threshold = 48;
	clearTimer(T1);
	while (true) {
		set_motors(40, 10);
		while (SensorValue(light) > threshold) {
			clearTimer(T1);
			set_motors(10, 40);
		}
	}
}

void set_motors(int b, int c) {
	motor[motorB] = b;
	motor[motorC] = c;
}
