#pragma config(Sensor, S4,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		nxtDisplayTextLine(3, "%d", SensorValue[lightSensor]);
		wait1Msec(50);
		nxtDisplayClearTextLine(3);
	}
}
