#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void pivot_turn(float degrees);
void forward(float revolutions);

task main() {
	nSyncedMotors = synchBC;
	while (true) {
		if (SensorValue(touch) == 0 && SensorValue(light) <= 48) {
			nSyncedTurnRatio = 100;
			motor[motorB] = 30;
		}
		else {
			forward(-1);
			wait1Msec(200);
			pivot_turn(180);
		}
	}
}

void pivot_turn(float degrees) {
	nSyncedTurnRatio = -100;
	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = 350 * (degrees/180);
	if (degrees > 0) {
		motor[motorB] = 20;
	}
	else {
		motor[motorB] = -20;
	}

	while(nMotorRunState[motorB] != runStateIdle) {}
	nSyncedTurnRatio = 100;
	motor[motorB] = 0;
}

void forward(float revolutions) {
	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = revolutions * 360;

	nSyncedTurnRatio = 100;
	if (revolutions > 0) {
		motor[motorB] = 30;
	}
	else {
		motor[motorB] = -30;
	}

	while(nMotorRunState[motorB] != runStateIdle) {}
}
