#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void pivot_turn(float degrees);
void forward(float revolutions);

task main()
{
	int turns = 0;
	while (turns < 12) {
		while (SensorValue[touch] != 1) {
			nSyncedMotors = synchBC;
			nSyncedTurnRatio = 100;
			motor[motorB] = 60;
		}
		motor[motorB] = 0;
		forward(-0.8);
		pivot_turn(90);
		wait1Msec(200);
		turns++;
	}
}

void pivot_turn(float degrees) {
	nSyncedMotors = synchNone;
	nSyncedMotors = synchBC;
	nSyncedTurnRatio = -100;

	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = (400) * (degrees/180);
	motor[motorB] = (degrees >= 0) ? 10 : -10;

	while(nMotorRunState[motorB] != runStateIdle) {}

	nSyncedMotors = synchNone;
	motor[motorB] = 0;
}

void forward(float revolutions) {
	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = revolutions * 360;

	nSyncedTurnRatio = 100;
	motor[motorB] = (revolutions > 0) ? 50 : -50;

	while(nMotorRunState[motorB] != runStateIdle) {}
}
