#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// 48 threshold

void pivot_turn(float degrees);
void forward(float revolutions);
void forward_cm(float cm);

task main()
{
	int threshold = 48;
	while (SensorValue(light) <= threshold) {
		nSyncedMotors = synchBC;
		nSyncedTurnRatio = 100;
		while (SensorValue[touch] == 0 && SensorValue(light) <= threshold) {
			motor[motorB] = 50;
		}
		motor[motorB] = 0;
		if (SensorValue(touch) == 1) {
			forward_cm(-7);
			wait1Msec(500);

			int turn = random(90) + 90;
			if (turn % 2 == 0) {
				turn = turn * -1;
			}
			pivot_turn(turn);
			wait1Msec(200);
		}
	}
}

void pivot_turn(float degrees) {
	nSyncedMotors = synchBC;
	nSyncedTurnRatio = -100;

	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = 360 * (degrees/180);
	motor[motorB] = (degrees >= 0) ? 30 : -30;

	while(nMotorRunState[motorB] != runStateIdle) {}

	nSyncedMotors = synchNone;
	motor[motorB] = 0;
}

void forward(float revolutions) {
	nSyncedMotors = synchBC;
	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = revolutions * 360;

	nSyncedTurnRatio = 100;
	motor[motorB] = (revolutions > 0) ? 50 : -50;

	while(nMotorRunState[motorB] != runStateIdle) {}
}

void forward_cm(float cm) {
	forward((5 * (cm / 90)) * 100/98);
}
