#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// 48 threshold

task main()
{
	int threshold = 48;
	int white_touches = 0;
	while (white_touches < 3) {
		motor[motorB] = 40;
		motor[motorC] = 40;
		if (SensorValue(light) >= threshold) {
			white_touches++;
		}
		wait1Msec(80);
	}
}
