#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void pivot_turn(float degrees);
void forward(float revolutions);

task main()
{
	nSyncedMotors = synchBC;
	while (true) {
		if (SensorValue[touchSensor] == 0) {
			nSyncedTurnRatio = 100;
			motor[motorB] = 80;
		}
		else {
			forward(-1);
			int n = random[2];
			if (n == 0) {
				pivot_turn(90);
			}
			else {
				pivot_turn(-90);
			}
		}
	}
}

void pivot_turn(float degrees) {
	nSyncedTurnRatio = -100;
	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = 390 * (degrees/180);
	if (degrees > 0) {
		motor[motorB] = 20;
	}
	else {
		motor[motorB] = -20;
	}

	while(nMotorRunState[motorB] != runStateIdle) {}
	nSyncedTurnRatio = 100;
	motor[motorB] = 0;
}

void forward(float revolutions) {
	nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = revolutions * 360;

	nSyncedTurnRatio = 100;
	if (revolutions > 0) {
		motor[motorB] = 50;
	}
	else {
		motor[motorB] = -50;
	}

	while(nMotorRunState[motorB] != runStateIdle) {}
}
