#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S4,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		int touched = SensorValue(touch);
		if (touched)
			nxtDisplayTextLine(3, "TOUCHED");
		else
			nxtDisplayTextLine(3, "NOT touched");
	}
	nxtDisplayTextLine(1, "TOUCHED");
	wait1Msec(2000);
}
